// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_hstop;
extern lv_obj_t *ui_hsleft;
extern lv_obj_t *ui_icnBle2;
extern lv_obj_t *ui_hsmid;
extern lv_obj_t *ui_lblTime2;
extern lv_obj_t *ui_msright;
extern lv_obj_t *ui_icnBatt2;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_btnRecent;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_btnActive2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_btnGoal2;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_goalArc2;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_btnStartRide2;
extern lv_obj_t *ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t *uic_hsleft;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

