// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_top;
lv_obj_t *ui_HomeScreen = NULL;lv_obj_t *ui_top = NULL;lv_obj_t *ui_left = NULL;lv_obj_t *ui_icnGps = NULL;lv_obj_t *ui_icnBle = NULL;lv_obj_t *ui_icnSearch = NULL;lv_obj_t *ui_mid = NULL;lv_obj_t *ui_lblTime = NULL;lv_obj_t *ui_right = NULL;lv_obj_t *ui_icnBatt = NULL;lv_obj_t *ui_Container5 = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_HomeScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_HomeScreen, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_flex_flow(ui_HomeScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HomeScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x2B90E6), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_top = lv_obj_create(ui_HomeScreen);
lv_obj_remove_style_all(ui_top);
lv_obj_set_width( ui_top, lv_pct(100));
lv_obj_set_height( ui_top, lv_pct(6));
lv_obj_set_flex_flow(ui_top,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_top, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_top, lv_color_hex(0x1979D5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_left = lv_obj_create(ui_top);
lv_obj_remove_style_all(ui_left);
lv_obj_set_width( ui_left, lv_pct(30));
lv_obj_set_height( ui_left, lv_pct(100));
lv_obj_set_align( ui_left, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_left,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_left, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icnGps = lv_label_create(ui_left);
lv_obj_set_height( ui_icnGps, lv_pct(100));
lv_obj_set_width( ui_icnGps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_icnGps, 8 );
lv_obj_set_y( ui_icnGps, 0 );
lv_obj_set_align( ui_icnGps, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnGps,"");
lv_obj_set_style_text_color(ui_icnGps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnGps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnGps, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_icnGps, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_icnGps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_icnGps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_icnGps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_icnGps, 225, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icnBle = lv_label_create(ui_left);
lv_obj_set_width( ui_icnBle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_icnBle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_icnBle, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnBle,"");
lv_obj_set_style_text_color(ui_icnBle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnBle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnBle, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icnSearch = lv_label_create(ui_left);
lv_obj_set_width( ui_icnSearch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_icnSearch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_icnSearch, 2 );
lv_obj_set_y( ui_icnSearch, 2 );
lv_obj_set_align( ui_icnSearch, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnSearch,"");
lv_obj_set_style_text_color(ui_icnSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnSearch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnSearch, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mid = lv_obj_create(ui_top);
lv_obj_remove_style_all(ui_mid);
lv_obj_set_width( ui_mid, lv_pct(40));
lv_obj_set_height( ui_mid, lv_pct(100));
lv_obj_set_align( ui_mid, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mid,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mid, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblTime = lv_label_create(ui_mid);
lv_obj_set_width( ui_lblTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTime, 25 );
lv_obj_set_y( ui_lblTime, 0 );
lv_obj_set_align( ui_lblTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime,"12:13 PM");
lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_right = lv_obj_create(ui_top);
lv_obj_remove_style_all(ui_right);
lv_obj_set_width( ui_right, lv_pct(30));
lv_obj_set_height( ui_right, lv_pct(100));
lv_obj_set_align( ui_right, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_right,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_right, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_right, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icnBatt = lv_label_create(ui_right);
lv_obj_set_width( ui_icnBatt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_icnBatt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_icnBatt, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnBatt,"");
lv_obj_set_style_text_color(ui_icnBatt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnBatt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnBatt, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_icnBatt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_icnBatt, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_icnBatt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_icnBatt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_HomeScreen);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(100));
lv_obj_set_height( ui_Container5, lv_pct(95));
lv_obj_set_x( ui_Container5, 0 );
lv_obj_set_y( ui_Container5, 32 );
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x1979D5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Container5, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Container5, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Container5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_top = ui_top;

}

void ui_HomeScreen_screen_destroy(void)
{
   if (ui_HomeScreen) lv_obj_del(ui_HomeScreen);

// NULL screen variables
ui_HomeScreen= NULL;
uic_top= NULL;
ui_top= NULL;
ui_left= NULL;
ui_icnGps= NULL;
ui_icnBle= NULL;
ui_icnSearch= NULL;
ui_mid= NULL;
ui_lblTime= NULL;
ui_right= NULL;
ui_icnBatt= NULL;
ui_Container5= NULL;

}
