// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_hsleft;
lv_obj_t *ui_HomeScreen = NULL;lv_obj_t *ui_hstop = NULL;lv_obj_t *ui_hsleft = NULL;lv_obj_t *ui_icnBle2 = NULL;lv_obj_t *ui_hsmid = NULL;lv_obj_t *ui_lblTime2 = NULL;lv_obj_t *ui_msright = NULL;lv_obj_t *ui_icnBatt2 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_btnRecent = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_btnActive2 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_btnGoal2 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_goalArc2 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_btnStartRide2 = NULL;lv_obj_t *ui_Label8 = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_HomeScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HomeScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_HomeScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x001031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_tiled(ui_HomeScreen, false, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hstop = lv_obj_create(ui_HomeScreen);
lv_obj_remove_style_all(ui_hstop);
lv_obj_set_width( ui_hstop, 240);
lv_obj_set_height( ui_hstop, 30);
lv_obj_set_x( ui_hstop, 32 );
lv_obj_set_y( ui_hstop, -64 );
lv_obj_set_align( ui_hstop, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_hstop,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_hstop, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_hstop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_hstop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hstop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_hstop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_hstop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hsleft = lv_obj_create(ui_hstop);
lv_obj_remove_style_all(ui_hsleft);
lv_obj_set_width( ui_hsleft, lv_pct(30));
lv_obj_set_height( ui_hsleft, lv_pct(100));
lv_obj_set_x( ui_hsleft, 85 );
lv_obj_set_y( ui_hsleft, 9 );
lv_obj_set_align( ui_hsleft, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_hsleft,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_hsleft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_hsleft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icnBle2 = lv_label_create(ui_hsleft);
lv_obj_set_height( ui_icnBle2, 20);
lv_obj_set_width( ui_icnBle2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_icnBle2, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnBle2,"");
lv_obj_set_style_text_color(ui_icnBle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnBle2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnBle2, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_icnBle2, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hsmid = lv_obj_create(ui_hstop);
lv_obj_remove_style_all(ui_hsmid);
lv_obj_set_width( ui_hsmid, lv_pct(41));
lv_obj_set_height( ui_hsmid, lv_pct(100));
lv_obj_set_align( ui_hsmid, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_hsmid,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_hsmid, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_hsmid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblTime2 = lv_label_create(ui_hsmid);
lv_obj_set_width( ui_lblTime2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTime2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTime2, 25 );
lv_obj_set_y( ui_lblTime2, 0 );
lv_obj_set_align( ui_lblTime2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime2,"12:13 PM");
lv_obj_set_style_text_color(ui_lblTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTime2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_msright = lv_obj_create(ui_hstop);
lv_obj_remove_style_all(ui_msright);
lv_obj_set_width( ui_msright, lv_pct(30));
lv_obj_set_height( ui_msright, lv_pct(100));
lv_obj_set_align( ui_msright, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_msright,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_msright, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_msright, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icnBatt2 = lv_label_create(ui_msright);
lv_obj_set_width( ui_icnBatt2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_icnBatt2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_icnBatt2, LV_ALIGN_CENTER );
lv_label_set_text(ui_icnBatt2,"");
lv_obj_set_style_text_color(ui_icnBatt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_icnBatt2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_icnBatt2, &ui_font_materialsmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_icnBatt2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_icnBatt2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_icnBatt2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_icnBatt2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_icnBatt2, 300, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_HomeScreen);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(90));
lv_obj_set_x( ui_Container1, 20 );
lv_obj_set_y( ui_Container1, 35 );
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_scroll_dir(ui_Container1, LV_DIR_VER);

ui_btnRecent = lv_button_create(ui_Container1);
lv_obj_set_width( ui_btnRecent, 130);
lv_obj_set_height( ui_btnRecent, 101);
lv_obj_set_x( ui_btnRecent, 0 );
lv_obj_set_y( ui_btnRecent, 164 );
lv_obj_set_align( ui_btnRecent, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnRecent, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnRecent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnRecent, 22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnRecent, lv_color_hex(0x8B20AC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnRecent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_btnRecent, lv_color_hex(0x8B20AC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_btnRecent, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_btnRecent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_btnRecent, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnRecent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnRecent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_btnRecent);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -4 );
lv_obj_set_y( ui_Label12, -17 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Recent");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &ui_font_JakartaSmlLBL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_btnRecent);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 2 );
lv_obj_set_y( ui_Label10, 4 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Yesterday: 32 KM");
lv_obj_set_style_text_font(ui_Label10, &ui_font_JakartaText, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_btnRecent);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, 0 );
lv_obj_set_y( ui_Label13, 29 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"View All >");
lv_obj_set_style_text_font(ui_Label13, &ui_font_JakartaText, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 180);
lv_obj_set_height( ui_Container3, 180);
lv_obj_set_x( ui_Container3, 0 );
lv_obj_set_y( ui_Container3, 38 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container3, 300, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x001031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xFF5D20), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container3, 11, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnActive2 = lv_button_create(ui_Container1);
lv_obj_set_width( ui_btnActive2, 97);
lv_obj_set_height( ui_btnActive2, 101);
lv_obj_set_x( ui_btnActive2, -55 );
lv_obj_set_y( ui_btnActive2, -86 );
lv_obj_set_align( ui_btnActive2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnActive2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnActive2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnActive2, 22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnActive2, lv_color_hex(0x3175C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnActive2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_btnActive2, lv_color_hex(0x3175C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_btnActive2, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_btnActive2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_btnActive2, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnActive2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnActive2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_btnActive2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -7 );
lv_obj_set_y( ui_Label1, -16 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Active\nRoute");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_JakartaSmlLBL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_btnActive2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 10 );
lv_obj_set_y( ui_Label2, 28 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Distance:\n45.2 km");
lv_obj_set_style_text_font(ui_Label2, &ui_font_JakartaText, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnGoal2 = lv_button_create(ui_Container1);
lv_obj_set_width( ui_btnGoal2, 98);
lv_obj_set_height( ui_btnGoal2, 101);
lv_obj_set_x( ui_btnGoal2, 55 );
lv_obj_set_y( ui_btnGoal2, -86 );
lv_obj_set_align( ui_btnGoal2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnGoal2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnGoal2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnGoal2, 22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnGoal2, lv_color_hex(0xC2EE39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnGoal2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_btnGoal2, lv_color_hex(0xBDEB3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_btnGoal2, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_btnGoal2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_btnGoal2, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnGoal2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnGoal2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_btnGoal2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, -17 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Training\nGoal");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_JakartaSmlLBL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_goalArc2 = lv_arc_create(ui_btnGoal2);
lv_obj_set_width( ui_goalArc2, 26);
lv_obj_set_height( ui_goalArc2, 26);
lv_obj_set_x( ui_goalArc2, 26 );
lv_obj_set_y( ui_goalArc2, 0 );
lv_obj_set_align( ui_goalArc2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_goalArc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_arc_set_value(ui_goalArc2, 75);
lv_arc_set_bg_angles(ui_goalArc2,0,360);
lv_obj_set_style_arc_color(ui_goalArc2, lv_color_hex(0x6AA908), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_goalArc2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_goalArc2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_goalArc2, lv_color_hex(0x020300), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_goalArc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_goalArc2, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_goalArc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_btnGoal2);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 1 );
lv_obj_set_y( ui_Label9, 28 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Weekly:\n150 / 200 km");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x020200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_JakartaText, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnStartRide2 = lv_button_create(ui_Container1);
lv_obj_set_width( ui_btnStartRide2, 140);
lv_obj_set_height( ui_btnStartRide2, 140);
lv_obj_set_x( ui_btnStartRide2, 0 );
lv_obj_set_y( ui_btnStartRide2, 38 );
lv_obj_set_align( ui_btnStartRide2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnStartRide2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnStartRide2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnStartRide2, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnStartRide2, lv_color_hex(0xFF5D18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnStartRide2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_btnStartRide2);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 0 );
lv_obj_set_y( ui_Label8, 4 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"RIDE");
lv_obj_set_style_text_font(ui_Label8, &ui_font_JakartaBigLBL, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_hsleft = ui_hsleft;

}

void ui_HomeScreen_screen_destroy(void)
{
   if (ui_HomeScreen) lv_obj_del(ui_HomeScreen);

// NULL screen variables
ui_HomeScreen= NULL;
ui_hstop= NULL;
uic_hsleft= NULL;
ui_hsleft= NULL;
ui_icnBle2= NULL;
ui_hsmid= NULL;
ui_lblTime2= NULL;
ui_msright= NULL;
ui_icnBatt2= NULL;
ui_Container1= NULL;
ui_btnRecent= NULL;
ui_Label12= NULL;
ui_Label10= NULL;
ui_Label13= NULL;
ui_Container3= NULL;
ui_btnActive2= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_btnGoal2= NULL;
ui_Label7= NULL;
ui_goalArc2= NULL;
ui_Label9= NULL;
ui_btnStartRide2= NULL;
ui_Label8= NULL;

}
