// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_top;
extern lv_obj_t *ui_left;
extern lv_obj_t *ui_icnGps;
extern lv_obj_t *ui_icnBle;
extern lv_obj_t *ui_icnSearch;
extern lv_obj_t *ui_mid;
extern lv_obj_t *ui_lblTime;
extern lv_obj_t *ui_right;
extern lv_obj_t *ui_icnBatt;
extern lv_obj_t *ui_Container5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_top;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

