// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Arc2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc2 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_Arc2, 150);
lv_obj_set_height( ui_Arc2, 47);
lv_obj_set_x( ui_Arc2, -25 );
lv_obj_set_y( ui_Arc2, -50 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc2, 50);
lv_arc_set_bg_angles(ui_Arc2,0,360);
lv_obj_set_style_arc_width(ui_Arc2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_Arc2, lv_color_hex(0xD01010), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc2, 66, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xF40505), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Arc2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Arc2, lv_color_hex(0x8C1414), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Arc2= NULL;

}
