// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_BrightOrange[1] = {0xFD5B1F};
const ui_theme_variable_t _ui_theme_alpha_BrightOrange[1] = {255};

const ui_theme_variable_t _ui_theme_color_BrightGreen[1] = {0xC1F23E};
const ui_theme_variable_t _ui_theme_alpha_BrightGreen[1] = {255};

const ui_theme_variable_t _ui_theme_color_BrightBlue[1] = {0x0058FF};
const ui_theme_variable_t _ui_theme_alpha_BrightBlue[1] = {255};

const ui_theme_variable_t _ui_theme_color_ThemePurple[1] = {0x8A22AD};
const ui_theme_variable_t _ui_theme_alpha_ThemePurple[1] = {255};

const ui_theme_variable_t _ui_theme_color_LightGreen[1] = {0xC2EA91};
const ui_theme_variable_t _ui_theme_alpha_LightGreen[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

