// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BRIGHTORANGE 0
#define UI_THEME_COLOR_BRIGHTGREEN 1
#define UI_THEME_COLOR_BRIGHTBLUE 2
#define UI_THEME_COLOR_THEMEPURPLE 3
#define UI_THEME_COLOR_LIGHTGREEN 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_BrightOrange[1];
extern const ui_theme_variable_t _ui_theme_alpha_BrightOrange[1];

extern const ui_theme_variable_t _ui_theme_color_BrightGreen[1];
extern const ui_theme_variable_t _ui_theme_alpha_BrightGreen[1];

extern const ui_theme_variable_t _ui_theme_color_BrightBlue[1];
extern const ui_theme_variable_t _ui_theme_alpha_BrightBlue[1];

extern const ui_theme_variable_t _ui_theme_color_ThemePurple[1];
extern const ui_theme_variable_t _ui_theme_alpha_ThemePurple[1];

extern const ui_theme_variable_t _ui_theme_color_LightGreen[1];
extern const ui_theme_variable_t _ui_theme_alpha_LightGreen[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
